version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.0
    working_directory: /go/src/github.com/bridge
    steps:
      - checkout
      - run: go test -v ./distribution/...
      - run: go test -v ./libdds/...
      - run: go test -v ./server/...